using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


namespace Mannheim.Salesforce.Client.RestApi.Describes
{
    public partial class DescribeObjectResult
    {
        public SObjectFieldsSet GetFieldSet() => new SObjectFieldsSet(this.Fields?.Select(f => f.Name));

        public string LabelOrApiName => string.IsNullOrEmpty(this.Label) ? "[" + this.ApiName + "]" : this.Label;

        public bool IsSystemObject => SystemObjectNames.Contains(this.ApiName);

        public static HashSet<string> SystemObjectNames = new HashSet<string>{
            "AcceptedEventRelation", "ActivityHistory", "Asset", "AttachedContentNotes", "Attachments", "CombinedAttachments", "AttachedContentDocument"
            , "ContentDistribution", "ContentDocumentLink", "ContentVersion", "DeclinedEventRelation", "DuplicateRecordItem"
            , "EntitySubscription", "EventRelation", "NoteAndAttachment", "ProcessInstance", "ProcessInstanceHistory", "RecordAction", "SocialPersona"
            ,                "ActionLinkGroupTemplate"
, "ActionLinkTemplate"
, "AggregateResult"
, "ApexClass"
, "ApexComponent"
, "ApexEmailNotification"
, "ApexLog"
, "ApexPage"
, "ApexPageInfo"
, "ApexTestQueueItem"
, "ApexTestResult"
, "ApexTestResultLimits"
, "ApexTestRunResult"
, "ApexTestSuite"
, "ApexTrigger"
, "AppDefinition"
, "AppMenuItem"
, "AppTabMember"
, "AssetTokenEvent"
, "AssignmentRule"
, "AsyncApexJob"
, "AuraDefinition"
, "AuraDefinitionBundle"
, "AuraDefinitionBundleInfo"
, "AuraDefinitionInfo"
, "AuthConfig"
, "AuthConfigProviders"
, "AuthProvider"
, "AuthSession"
, "BackgroundOperation"
, "BatchApexErrorEvent"
, "CallCenter"
, "ChatterActivity"
, "ChatterExtension"
, "ChatterExtensionConfig"
, "ClientBrowser"
, "Community"
, "ConnectedApplication"
, "CorsWhitelistEntry"
, "CronJobDetail"
, "CronTrigger"
, "CspTrustedSite"
, "CustomObjectUserLicenseMetrics"
, "CustomPermission"
, "CustomPermissionDependency"
, "DatacloudAddress"
, "DataIntegrationRecordPurchasePermission"
, "DataStatistics"
, "DataType"
, "Domain"
, "DomainSite"
, "EmbeddedServiceDetail"
, "EntityDefinition"
, "EntityParticle"
, "EntitySubscription"
, "ExternalDataSource"
, "ExternalDataUserAuth"
, "FieldDefinition"
, "FieldPermissions"
, "FileSearchActivity"
, "GrantedByLicense"
, "Group"
, "GroupMember"
, "IconDefinition"
, "IdpEventLog"
, "InstalledMobileApp"
, "LightningComponentBundle"
, "LightningComponentResource"
, "LightningComponentTag"
, "LightningExperienceTheme"
, "ListEmail"
, "ListEmailRecipientSource"
, "ListView"
, "ListViewChart"
, "ListViewChartInstance"
, "LoginGeo"
, "LoginIp"
, "LookedUpFromActivity"
, "Macro"
, "MacroInstruction"
, "NamedCredential"
, "OauthToken"
, "ObjectPermissions"
, "Organization"
, "OrgLifecycleNotification"
, "OrgWideEmailAddress"
, "OwnerChangeOptionInfo"
, "PackageLicense"
, "Period"
, "PermissionSet"
, "PermissionSetAssignment"
, "PermissionSetLicense"
, "PermissionSetLicenseAssign"
, "PicklistValueInfo"
, "PlatformAction"
, "PlatformCachePartition"
, "PlatformCachePartitionType"
, "ProcessDefinition"
, "ProcessInstance"
, "ProcessInstanceNode"
, "ProcessInstanceStep"
, "ProcessInstanceWorkitem"
, "ProcessNode"
, "Profile"
, "Publisher"
, "PushTopic"
, "QualifiedApiName"
, "QueueSobject"
, "RecentlyViewed"
, "RecordAction"
, "RecordType"
, "RelationshipDomain"
, "RelationshipInfo"
, "Report"
, "SamlSsoConfig"
, "Scontrol"
, "SearchActivity"
, "SearchLayout"
, "SearchPromotionRule"
, "SecureAgentsCluster"
, "SecurityCustomBaseline"
, "SessionPermSetActivation"
, "SetupAuditTrail"
, "SetupEntityAccess"
, "Site"
, "StaticResource"
, "StreamingChannel"
, "TabDefinition"
, "TenantUsageEntitlement"
, "TestSuiteMembership"
, "UndecidedEventRelation"
, "User"
, "UserAppInfo"
, "UserAppMenuCustomization"
, "UserAppMenuItem"
, "UserEntityAccess"
, "UserFieldAccess"
, "UserLicense"
, "UserListView"
, "UserListViewCriterion"
, "UserLogin"
, "UserPackageLicense"
, "UserPermissionAccess"
, "UserPreference"
, "UserRecordAccess"
, "UserRole"
, "VisibilityChangeNotification"
, "VisualforceAccessMetrics"
, "WaveAutoInstallRequest"
, "WaveCompatibilityCheckItem"
, "WebLink"
            };
    }
}
